// Generated by FIR Compiler
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
// ************************************************************
// Copyright (C) 1991-2004 Altera Corporation
// Any megafunction design, and related net list (encrypted or decrypted),
// support information, device programming or simulation file, and any other
// associated documentation or information provided by Altera or a partner
// under Altera's Megafunction Partnership Program may be used only to
// program PLD devices (but not masked PLD devices) from Altera.  Any other
// use of such megafunction design, net list, support information, device
// programming or simulation file, or any other related documentation or
// information is prohibited for any other purpose, including, but not
// limited to modification, reverse engineering, de-compiling, or use with
// any other silicon devices, unless such use is explicitly licensed under
// a separate agreement with Altera or a megafunction partner.  Title to
// the intellectual property, including patents, copyrights, trademarks,
// trade secrets, or maskworks, embodied in any such megafunction design,
// net list, support information, device programming or simulation file, or
// any other related documentation or information provided by Altera or a
// megafunction partner, remains with Altera, the megafunction partner, or
// their respective licensors.  No other licenses, including any licenses
// needed under any third party's intellectual property, are provided herein.
// 01
// altera message_off 10036
(* altera_attribute = "-name MESSAGE_DISABLE 15400; -name MESSAGE_DISABLE 14130; -name MESSAGE_DISABLE 10036; -name MESSAGE_DISABLE 12020; -name MESSAGE_DISABLE 12030; -name MESSAGE_DISABLE 12010; -name MESSAGE_DISABLE 12110; -name MESSAGE_DISABLE 14320; -name MESSAGE_DISABLE 13410" *)
module filter_st (clk, 
              rst, 
              data_in, 
              clk_en, 
              coef_set, 
              done, 
              rdy_to_ld, 
              fir_result ); 

parameter DATA_WIDTH  = 10;
parameter COEF_WIDTH  = 8;
parameter COEF_WIDTH_IN  = 8;
parameter ACCUM_WIDTH = 21;

parameter COEF_SET_WIDTH = 1;

input clk, rst;
input [DATA_WIDTH -1 :0] data_in;
input clk_en;
input [COEF_SET_WIDTH-1:0] coef_set;
output done;
wire done;
wire done_int;
wire data_ld;
output rdy_to_ld;
wire rdy_to_ld;
wire rdy_int;
output [ACCUM_WIDTH-1:0] fir_result;

wire acc_rst_out;
wire coef_in_clk;
assign coef_in_clk = clk;
wire [9:0] tdl_dat_0_n;
wire [9:0] tdl_dat_1_n;
wire [9:0] tdl_dat_2_n;
wire [9:0] tdl_dat_3_n;
wire [9:0] tdl_dat_4_n;
wire [9:0] tdl_dat_5_n;
wire [9:0] tdl_dat_6_n;
wire [9:0] tdl_dat_7_n;
wire [9:0] tdl_dat_8_n;
wire [9:0] tdl_dat_9_n;
wire [9:0] tdl_dat_10_n;
wire [9:0] tdl_dat_11_n;
wire [9:0] tdl_dat_12_n;
wire [9:0] data_in_mux;
mux_2to1_cen tdl_mux(.clk(clk), .rst(rst), .gclk_en(clk_en), .bin(tdl_dat_12_n), .ain(data_in),
 .data_out(data_in_mux), .sel(rdy_int));
defparam tdl_mux.IN_WIDTH = 10;
msft_data tdl_ff_0_ch_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(data_in_mux),.data_out(tdl_dat_0_n));
defparam tdl_ff_0_ch_0_n.WIDTH = 10;
defparam tdl_ff_0_ch_0_n.LENGTH = 4;
defparam tdl_ff_0_ch_0_n.DELAY = 0;
msft_data tdl_ff_1_ch_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(tdl_dat_0_n),.data_out(tdl_dat_1_n));
defparam tdl_ff_1_ch_0_n.WIDTH = 10;
defparam tdl_ff_1_ch_0_n.LENGTH = 4;
defparam tdl_ff_1_ch_0_n.DELAY = 0;
msft_data tdl_ff_2_ch_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(tdl_dat_1_n),.data_out(tdl_dat_2_n));
defparam tdl_ff_2_ch_0_n.WIDTH = 10;
defparam tdl_ff_2_ch_0_n.LENGTH = 4;
defparam tdl_ff_2_ch_0_n.DELAY = 0;
msft_data tdl_ff_3_ch_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(tdl_dat_2_n),.data_out(tdl_dat_3_n));
defparam tdl_ff_3_ch_0_n.WIDTH = 10;
defparam tdl_ff_3_ch_0_n.LENGTH = 4;
defparam tdl_ff_3_ch_0_n.DELAY = 0;
msft_data tdl_ff_4_ch_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(tdl_dat_3_n),.data_out(tdl_dat_4_n));
defparam tdl_ff_4_ch_0_n.WIDTH = 10;
defparam tdl_ff_4_ch_0_n.LENGTH = 4;
defparam tdl_ff_4_ch_0_n.DELAY = 0;
msft_data tdl_ff_5_ch_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(tdl_dat_4_n),.data_out(tdl_dat_5_n));
defparam tdl_ff_5_ch_0_n.WIDTH = 10;
defparam tdl_ff_5_ch_0_n.LENGTH = 4;
defparam tdl_ff_5_ch_0_n.DELAY = 0;
msft_data tdl_ff_6_ch_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(tdl_dat_5_n),.data_out(tdl_dat_6_n));
defparam tdl_ff_6_ch_0_n.WIDTH = 10;
defparam tdl_ff_6_ch_0_n.LENGTH = 4;
defparam tdl_ff_6_ch_0_n.DELAY = 0;
msft_data tdl_ff_7_ch_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(tdl_dat_6_n),.data_out(tdl_dat_7_n));
defparam tdl_ff_7_ch_0_n.WIDTH = 10;
defparam tdl_ff_7_ch_0_n.LENGTH = 4;
defparam tdl_ff_7_ch_0_n.DELAY = 0;
msft_data tdl_ff_8_ch_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(tdl_dat_7_n),.data_out(tdl_dat_8_n));
defparam tdl_ff_8_ch_0_n.WIDTH = 10;
defparam tdl_ff_8_ch_0_n.LENGTH = 4;
defparam tdl_ff_8_ch_0_n.DELAY = 0;
msft_data tdl_ff_9_ch_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(tdl_dat_8_n),.data_out(tdl_dat_9_n));
defparam tdl_ff_9_ch_0_n.WIDTH = 10;
defparam tdl_ff_9_ch_0_n.LENGTH = 4;
defparam tdl_ff_9_ch_0_n.DELAY = 0;
msft_data tdl_ff_10_ch_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(tdl_dat_9_n),.data_out(tdl_dat_10_n));
defparam tdl_ff_10_ch_0_n.WIDTH = 10;
defparam tdl_ff_10_ch_0_n.LENGTH = 4;
defparam tdl_ff_10_ch_0_n.DELAY = 0;
msft_data tdl_ff_11_ch_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(tdl_dat_10_n),.data_out(tdl_dat_11_n));
defparam tdl_ff_11_ch_0_n.WIDTH = 10;
defparam tdl_ff_11_ch_0_n.LENGTH = 4;
defparam tdl_ff_11_ch_0_n.DELAY = 0;
msft_data tdl_ff_12_ch_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(tdl_dat_11_n),.data_out(tdl_dat_12_n));
defparam tdl_ff_12_ch_0_n.WIDTH = 10;
defparam tdl_ff_12_ch_0_n.LENGTH = 4;
defparam tdl_ff_12_ch_0_n.DELAY = 0;
wire [9:0] tdl_dat_0_n_d;
lc_store_cen tdl_dd_0_n (.rst(rst), .clk(clk), .ce(1'b1), .gclk_en(clk_en), .data_in(tdl_dat_0_n), .q(tdl_dat_0_n_d) );
defparam tdl_dd_0_n.WIDTH = 10;
wire [9:0] tdl_dat_1_n_d;
lc_store_cen tdl_dd_1_n (.rst(rst), .clk(clk), .ce(1'b1), .gclk_en(clk_en), .data_in(tdl_dat_1_n), .q(tdl_dat_1_n_d) );
defparam tdl_dd_1_n.WIDTH = 10;
wire [9:0] tdl_dat_2_n_d;
lc_store_cen tdl_dd_2_n (.rst(rst), .clk(clk), .ce(1'b1), .gclk_en(clk_en), .data_in(tdl_dat_2_n), .q(tdl_dat_2_n_d) );
defparam tdl_dd_2_n.WIDTH = 10;
wire [9:0] tdl_dat_3_n_d;
lc_store_cen tdl_dd_3_n (.rst(rst), .clk(clk), .ce(1'b1), .gclk_en(clk_en), .data_in(tdl_dat_3_n), .q(tdl_dat_3_n_d) );
defparam tdl_dd_3_n.WIDTH = 10;
wire [9:0] tdl_dat_4_n_d;
lc_store_cen tdl_dd_4_n (.rst(rst), .clk(clk), .ce(1'b1), .gclk_en(clk_en), .data_in(tdl_dat_4_n), .q(tdl_dat_4_n_d) );
defparam tdl_dd_4_n.WIDTH = 10;
wire [9:0] tdl_dat_5_n_d;
lc_store_cen tdl_dd_5_n (.rst(rst), .clk(clk), .ce(1'b1), .gclk_en(clk_en), .data_in(tdl_dat_5_n), .q(tdl_dat_5_n_d) );
defparam tdl_dd_5_n.WIDTH = 10;
wire [9:0] tdl_dat_6_n_d;
lc_store_cen tdl_dd_6_n (.rst(rst), .clk(clk), .ce(1'b1), .gclk_en(clk_en), .data_in(tdl_dat_6_n), .q(tdl_dat_6_n_d) );
defparam tdl_dd_6_n.WIDTH = 10;
wire [9:0] tdl_dat_7_n_d;
lc_store_cen tdl_dd_7_n (.rst(rst), .clk(clk), .ce(1'b1), .gclk_en(clk_en), .data_in(tdl_dat_7_n), .q(tdl_dat_7_n_d) );
defparam tdl_dd_7_n.WIDTH = 10;
wire [9:0] tdl_dat_8_n_d;
lc_store_cen tdl_dd_8_n (.rst(rst), .clk(clk), .ce(1'b1), .gclk_en(clk_en), .data_in(tdl_dat_8_n), .q(tdl_dat_8_n_d) );
defparam tdl_dd_8_n.WIDTH = 10;
wire [9:0] tdl_dat_9_n_d;
lc_store_cen tdl_dd_9_n (.rst(rst), .clk(clk), .ce(1'b1), .gclk_en(clk_en), .data_in(tdl_dat_9_n), .q(tdl_dat_9_n_d) );
defparam tdl_dd_9_n.WIDTH = 10;
wire [9:0] tdl_dat_10_n_d;
lc_store_cen tdl_dd_10_n (.rst(rst), .clk(clk), .ce(1'b1), .gclk_en(clk_en), .data_in(tdl_dat_10_n), .q(tdl_dat_10_n_d) );
defparam tdl_dd_10_n.WIDTH = 10;
wire [9:0] tdl_dat_11_n_d;
lc_store_cen tdl_dd_11_n (.rst(rst), .clk(clk), .ce(1'b1), .gclk_en(clk_en), .data_in(tdl_dat_11_n), .q(tdl_dat_11_n_d) );
defparam tdl_dd_11_n.WIDTH = 10;
wire [9:0] tdl_dat_12_n_d;
lc_store_cen tdl_dd_12_n (.rst(rst), .clk(clk), .ce(1'b1), .gclk_en(clk_en), .data_in(tdl_dat_12_n), .q(tdl_dat_12_n_d) );
defparam tdl_dd_12_n.WIDTH = 10;

wire [COEF_SET_WIDTH-1 :0]coef_set_dly;
wire [COEF_WIDTH-1 :0]coef_in_dly;
lc_store_cen Coef_in_reg (.clk(clk), .ce(1'b1),
.rst(rst), .gclk_en(clk_en),.data_in(coef_in), .q(coef_in_dly) );
defparam Coef_in_reg.WIDTH = COEF_WIDTH;
delay_trig_cen coef_set_reg(.clk(clk), .rst(rst),.gclk_en(clk_en),.enable(rdy_int), .data_in(coef_set),.data_out(coef_set_dly));
defparam coef_set_reg.IN_WIDTH = COEF_SET_WIDTH;
defparam coef_set_reg.WHOLE_DELAY = 1;
defparam coef_set_reg.FINE_DELAY = 4;
wire [1 : 0] coef_set_we ;
decoder_we decoder(.clk(clk),.rst(rst),.we(coef_we),.clk_en(clk_en),.data_in(coef_set_in),.en_out(coef_set_we));
defparam decoder.DATA_ADDR_WIDTH = 1;
defparam decoder.OUT_WIDTH = 2;
wire [7:0] coef_st_0_mac_0_n;
msft_lt_32 Ucoef_set_0_mac_0_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[0]), .data_in(coef_in_dly), .data_out(coef_st_0_mac_0_n));
defparam Ucoef_set_0_mac_0_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_0_mac_0_n.LENGTH = 4;
defparam Ucoef_set_0_mac_0_n.DELAY = 0;
defparam Ucoef_set_0_mac_0_n.C0 = 0;
defparam Ucoef_set_0_mac_0_n.C1 = 0;
defparam Ucoef_set_0_mac_0_n.C2 = 0;
defparam Ucoef_set_0_mac_0_n.C3 = 0;
wire [7:0] coef_st_0_mac_1_n;
msft_lt_32 Ucoef_set_0_mac_1_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[0]), .data_in(coef_st_0_mac_0_n), .data_out(coef_st_0_mac_1_n));
defparam Ucoef_set_0_mac_1_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_0_mac_1_n.LENGTH = 4;
defparam Ucoef_set_0_mac_1_n.DELAY = 0;
defparam Ucoef_set_0_mac_1_n.C0 = 0;
defparam Ucoef_set_0_mac_1_n.C1 = 0;
defparam Ucoef_set_0_mac_1_n.C2 = 0;
defparam Ucoef_set_0_mac_1_n.C3 = 0;
wire [7:0] coef_st_0_mac_2_n;
msft_lt_32 Ucoef_set_0_mac_2_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[0]), .data_in(coef_st_0_mac_1_n), .data_out(coef_st_0_mac_2_n));
defparam Ucoef_set_0_mac_2_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_0_mac_2_n.LENGTH = 4;
defparam Ucoef_set_0_mac_2_n.DELAY = 0;
defparam Ucoef_set_0_mac_2_n.C0 = 0;
defparam Ucoef_set_0_mac_2_n.C1 = 0;
defparam Ucoef_set_0_mac_2_n.C2 = 0;
defparam Ucoef_set_0_mac_2_n.C3 = 0;
wire [7:0] coef_st_0_mac_3_n;
msft_lt_32 Ucoef_set_0_mac_3_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[0]), .data_in(coef_st_0_mac_2_n), .data_out(coef_st_0_mac_3_n));
defparam Ucoef_set_0_mac_3_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_0_mac_3_n.LENGTH = 4;
defparam Ucoef_set_0_mac_3_n.DELAY = 0;
defparam Ucoef_set_0_mac_3_n.C0 = 0;
defparam Ucoef_set_0_mac_3_n.C1 = 0;
defparam Ucoef_set_0_mac_3_n.C2 = 0;
defparam Ucoef_set_0_mac_3_n.C3 = 0;
wire [7:0] coef_st_0_mac_4_n;
msft_lt_32 Ucoef_set_0_mac_4_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[0]), .data_in(coef_st_0_mac_3_n), .data_out(coef_st_0_mac_4_n));
defparam Ucoef_set_0_mac_4_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_0_mac_4_n.LENGTH = 4;
defparam Ucoef_set_0_mac_4_n.DELAY = 0;
defparam Ucoef_set_0_mac_4_n.C0 = 0;
defparam Ucoef_set_0_mac_4_n.C1 = 0;
defparam Ucoef_set_0_mac_4_n.C2 = 0;
defparam Ucoef_set_0_mac_4_n.C3 = 0;
wire [7:0] coef_st_0_mac_5_n;
msft_lt_32 Ucoef_set_0_mac_5_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[0]), .data_in(coef_st_0_mac_4_n), .data_out(coef_st_0_mac_5_n));
defparam Ucoef_set_0_mac_5_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_0_mac_5_n.LENGTH = 4;
defparam Ucoef_set_0_mac_5_n.DELAY = 0;
defparam Ucoef_set_0_mac_5_n.C0 = 0;
defparam Ucoef_set_0_mac_5_n.C1 = 0;
defparam Ucoef_set_0_mac_5_n.C2 = 0;
defparam Ucoef_set_0_mac_5_n.C3 = 0;
wire [7:0] coef_st_0_mac_6_n;
msft_lt_32 Ucoef_set_0_mac_6_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[0]), .data_in(coef_st_0_mac_5_n), .data_out(coef_st_0_mac_6_n));
defparam Ucoef_set_0_mac_6_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_0_mac_6_n.LENGTH = 4;
defparam Ucoef_set_0_mac_6_n.DELAY = 0;
defparam Ucoef_set_0_mac_6_n.C0 = 0;
defparam Ucoef_set_0_mac_6_n.C1 = 0;
defparam Ucoef_set_0_mac_6_n.C2 = 0;
defparam Ucoef_set_0_mac_6_n.C3 = 0;
wire [7:0] coef_st_0_mac_7_n;
msft_lt_32 Ucoef_set_0_mac_7_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[0]), .data_in(coef_st_0_mac_6_n), .data_out(coef_st_0_mac_7_n));
defparam Ucoef_set_0_mac_7_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_0_mac_7_n.LENGTH = 4;
defparam Ucoef_set_0_mac_7_n.DELAY = 0;
defparam Ucoef_set_0_mac_7_n.C0 = 0;
defparam Ucoef_set_0_mac_7_n.C1 = 0;
defparam Ucoef_set_0_mac_7_n.C2 = 0;
defparam Ucoef_set_0_mac_7_n.C3 = 0;
wire [7:0] coef_st_0_mac_8_n;
msft_lt_32 Ucoef_set_0_mac_8_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[0]), .data_in(coef_st_0_mac_7_n), .data_out(coef_st_0_mac_8_n));
defparam Ucoef_set_0_mac_8_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_0_mac_8_n.LENGTH = 4;
defparam Ucoef_set_0_mac_8_n.DELAY = 0;
defparam Ucoef_set_0_mac_8_n.C0 = 0;
defparam Ucoef_set_0_mac_8_n.C1 = 0;
defparam Ucoef_set_0_mac_8_n.C2 = 0;
defparam Ucoef_set_0_mac_8_n.C3 = 0;
wire [7:0] coef_st_0_mac_9_n;
msft_lt_32 Ucoef_set_0_mac_9_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[0]), .data_in(coef_st_0_mac_8_n), .data_out(coef_st_0_mac_9_n));
defparam Ucoef_set_0_mac_9_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_0_mac_9_n.LENGTH = 4;
defparam Ucoef_set_0_mac_9_n.DELAY = 0;
defparam Ucoef_set_0_mac_9_n.C0 = 0;
defparam Ucoef_set_0_mac_9_n.C1 = 0;
defparam Ucoef_set_0_mac_9_n.C2 = 0;
defparam Ucoef_set_0_mac_9_n.C3 = 0;
wire [7:0] coef_st_0_mac_10_n;
msft_lt_32 Ucoef_set_0_mac_10_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[0]), .data_in(coef_st_0_mac_9_n), .data_out(coef_st_0_mac_10_n));
defparam Ucoef_set_0_mac_10_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_0_mac_10_n.LENGTH = 4;
defparam Ucoef_set_0_mac_10_n.DELAY = 0;
defparam Ucoef_set_0_mac_10_n.C0 = 0;
defparam Ucoef_set_0_mac_10_n.C1 = 0;
defparam Ucoef_set_0_mac_10_n.C2 = 0;
defparam Ucoef_set_0_mac_10_n.C3 = 0;
wire [7:0] coef_st_0_mac_11_n;
msft_lt_32 Ucoef_set_0_mac_11_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[0]), .data_in(coef_st_0_mac_10_n), .data_out(coef_st_0_mac_11_n));
defparam Ucoef_set_0_mac_11_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_0_mac_11_n.LENGTH = 4;
defparam Ucoef_set_0_mac_11_n.DELAY = 0;
defparam Ucoef_set_0_mac_11_n.C0 = 0;
defparam Ucoef_set_0_mac_11_n.C1 = 0;
defparam Ucoef_set_0_mac_11_n.C2 = 0;
defparam Ucoef_set_0_mac_11_n.C3 = 0;
wire [7:0] coef_st_0_mac_12_n;
msft_lt_32 Ucoef_set_0_mac_12_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[0]), .data_in(coef_st_0_mac_11_n), .data_out(coef_st_0_mac_12_n));
defparam Ucoef_set_0_mac_12_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_0_mac_12_n.LENGTH = 4;
defparam Ucoef_set_0_mac_12_n.DELAY = 0;
defparam Ucoef_set_0_mac_12_n.C0 = 0;
defparam Ucoef_set_0_mac_12_n.C1 = 0;
defparam Ucoef_set_0_mac_12_n.C2 = 0;
defparam Ucoef_set_0_mac_12_n.C3 = 0;


wire [7:0] coef_st_1_mac_0_n;
msft_lt_32 Ucoef_set_1_mac_0_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[1]), .data_in(coef_in_dly), .data_out(coef_st_1_mac_0_n));
defparam Ucoef_set_1_mac_0_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_1_mac_0_n.LENGTH = 4;
defparam Ucoef_set_1_mac_0_n.DELAY = 0;
defparam Ucoef_set_1_mac_0_n.C0 = 108;
defparam Ucoef_set_1_mac_0_n.C1 = 243;
defparam Ucoef_set_1_mac_0_n.C2 = 0;
defparam Ucoef_set_1_mac_0_n.C3 = 4;
wire [7:0] coef_st_1_mac_1_n;
msft_lt_32 Ucoef_set_1_mac_1_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[1]), .data_in(coef_st_1_mac_0_n), .data_out(coef_st_1_mac_1_n));
defparam Ucoef_set_1_mac_1_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_1_mac_1_n.LENGTH = 4;
defparam Ucoef_set_1_mac_1_n.DELAY = 0;
defparam Ucoef_set_1_mac_1_n.C0 = 88;
defparam Ucoef_set_1_mac_1_n.C1 = 239;
defparam Ucoef_set_1_mac_1_n.C2 = 0;
defparam Ucoef_set_1_mac_1_n.C3 = 4;
wire [7:0] coef_st_1_mac_2_n;
msft_lt_32 Ucoef_set_1_mac_2_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[1]), .data_in(coef_st_1_mac_1_n), .data_out(coef_st_1_mac_2_n));
defparam Ucoef_set_1_mac_2_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_1_mac_2_n.LENGTH = 4;
defparam Ucoef_set_1_mac_2_n.DELAY = 0;
defparam Ucoef_set_1_mac_2_n.C0 = 64;
defparam Ucoef_set_1_mac_2_n.C1 = 239;
defparam Ucoef_set_1_mac_2_n.C2 = 255;
defparam Ucoef_set_1_mac_2_n.C3 = 3;
wire [7:0] coef_st_1_mac_3_n;
msft_lt_32 Ucoef_set_1_mac_3_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[1]), .data_in(coef_st_1_mac_2_n), .data_out(coef_st_1_mac_3_n));
defparam Ucoef_set_1_mac_3_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_1_mac_3_n.LENGTH = 4;
defparam Ucoef_set_1_mac_3_n.DELAY = 0;
defparam Ucoef_set_1_mac_3_n.C0 = 40;
defparam Ucoef_set_1_mac_3_n.C1 = 245;
defparam Ucoef_set_1_mac_3_n.C2 = 254;
defparam Ucoef_set_1_mac_3_n.C3 = 1;
wire [7:0] coef_st_1_mac_4_n;
msft_lt_32 Ucoef_set_1_mac_4_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[1]), .data_in(coef_st_1_mac_3_n), .data_out(coef_st_1_mac_4_n));
defparam Ucoef_set_1_mac_4_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_1_mac_4_n.LENGTH = 4;
defparam Ucoef_set_1_mac_4_n.DELAY = 0;
defparam Ucoef_set_1_mac_4_n.C0 = 17;
defparam Ucoef_set_1_mac_4_n.C1 = 0;
defparam Ucoef_set_1_mac_4_n.C2 = 255;
defparam Ucoef_set_1_mac_4_n.C3 = 0;
wire [7:0] coef_st_1_mac_5_n;
msft_lt_32 Ucoef_set_1_mac_5_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[1]), .data_in(coef_st_1_mac_4_n), .data_out(coef_st_1_mac_5_n));
defparam Ucoef_set_1_mac_5_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_1_mac_5_n.LENGTH = 4;
defparam Ucoef_set_1_mac_5_n.DELAY = 0;
defparam Ucoef_set_1_mac_5_n.C0 = 0;
defparam Ucoef_set_1_mac_5_n.C1 = 17;
defparam Ucoef_set_1_mac_5_n.C2 = 0;
defparam Ucoef_set_1_mac_5_n.C3 = 255;
wire [7:0] coef_st_1_mac_6_n;
msft_lt_32 Ucoef_set_1_mac_6_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[1]), .data_in(coef_st_1_mac_5_n), .data_out(coef_st_1_mac_6_n));
defparam Ucoef_set_1_mac_6_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_1_mac_6_n.LENGTH = 4;
defparam Ucoef_set_1_mac_6_n.DELAY = 0;
defparam Ucoef_set_1_mac_6_n.C0 = 245;
defparam Ucoef_set_1_mac_6_n.C1 = 40;
defparam Ucoef_set_1_mac_6_n.C2 = 1;
defparam Ucoef_set_1_mac_6_n.C3 = 254;
wire [7:0] coef_st_1_mac_7_n;
msft_lt_32 Ucoef_set_1_mac_7_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[1]), .data_in(coef_st_1_mac_6_n), .data_out(coef_st_1_mac_7_n));
defparam Ucoef_set_1_mac_7_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_1_mac_7_n.LENGTH = 4;
defparam Ucoef_set_1_mac_7_n.DELAY = 0;
defparam Ucoef_set_1_mac_7_n.C0 = 239;
defparam Ucoef_set_1_mac_7_n.C1 = 64;
defparam Ucoef_set_1_mac_7_n.C2 = 3;
defparam Ucoef_set_1_mac_7_n.C3 = 255;
wire [7:0] coef_st_1_mac_8_n;
msft_lt_32 Ucoef_set_1_mac_8_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[1]), .data_in(coef_st_1_mac_7_n), .data_out(coef_st_1_mac_8_n));
defparam Ucoef_set_1_mac_8_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_1_mac_8_n.LENGTH = 4;
defparam Ucoef_set_1_mac_8_n.DELAY = 0;
defparam Ucoef_set_1_mac_8_n.C0 = 239;
defparam Ucoef_set_1_mac_8_n.C1 = 88;
defparam Ucoef_set_1_mac_8_n.C2 = 4;
defparam Ucoef_set_1_mac_8_n.C3 = 0;
wire [7:0] coef_st_1_mac_9_n;
msft_lt_32 Ucoef_set_1_mac_9_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[1]), .data_in(coef_st_1_mac_8_n), .data_out(coef_st_1_mac_9_n));
defparam Ucoef_set_1_mac_9_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_1_mac_9_n.LENGTH = 4;
defparam Ucoef_set_1_mac_9_n.DELAY = 0;
defparam Ucoef_set_1_mac_9_n.C0 = 243;
defparam Ucoef_set_1_mac_9_n.C1 = 108;
defparam Ucoef_set_1_mac_9_n.C2 = 4;
defparam Ucoef_set_1_mac_9_n.C3 = 0;
wire [7:0] coef_st_1_mac_10_n;
msft_lt_32 Ucoef_set_1_mac_10_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[1]), .data_in(coef_st_1_mac_9_n), .data_out(coef_st_1_mac_10_n));
defparam Ucoef_set_1_mac_10_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_1_mac_10_n.LENGTH = 4;
defparam Ucoef_set_1_mac_10_n.DELAY = 0;
defparam Ucoef_set_1_mac_10_n.C0 = 248;
defparam Ucoef_set_1_mac_10_n.C1 = 122;
defparam Ucoef_set_1_mac_10_n.C2 = 1;
defparam Ucoef_set_1_mac_10_n.C3 = 0;
wire [7:0] coef_st_1_mac_11_n;
msft_lt_32 Ucoef_set_1_mac_11_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[1]), .data_in(coef_st_1_mac_10_n), .data_out(coef_st_1_mac_11_n));
defparam Ucoef_set_1_mac_11_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_1_mac_11_n.LENGTH = 4;
defparam Ucoef_set_1_mac_11_n.DELAY = 0;
defparam Ucoef_set_1_mac_11_n.C0 = 254;
defparam Ucoef_set_1_mac_11_n.C1 = 127;
defparam Ucoef_set_1_mac_11_n.C2 = 254;
defparam Ucoef_set_1_mac_11_n.C3 = 0;
wire [7:0] coef_st_1_mac_12_n;
msft_lt_32 Ucoef_set_1_mac_12_n (.rst(rst), .clk(clk),.clk_en(clk_en), .we(coef_set_we[1]), .data_in(coef_st_1_mac_11_n), .data_out(coef_st_1_mac_12_n));
defparam Ucoef_set_1_mac_12_n.WIDTH = COEF_WIDTH;
defparam Ucoef_set_1_mac_12_n.LENGTH = 4;
defparam Ucoef_set_1_mac_12_n.DELAY = 0;
defparam Ucoef_set_1_mac_12_n.C0 = 1;
defparam Ucoef_set_1_mac_12_n.C1 = 122;
defparam Ucoef_set_1_mac_12_n.C2 = 248;
defparam Ucoef_set_1_mac_12_n.C3 = 0;


wire [7:0]coef_set_ext;
assign coef_set_ext = {7'b0, coef_set_dly};
wire [7:0] coef_st_0_n;
mux_16_cen Umux_coef_0_n (.clk(clk),
.gclk_en(clk_en),.data_0_in(coef_st_0_mac_0_n),
.data_1_in(coef_st_1_mac_0_n),
.data_out(coef_st_0_n),
.sel(coef_set_ext));
defparam Umux_coef_0_n.IN_WIDTH = COEF_WIDTH;
wire [7:0] coef_st_1_n;
mux_16_cen Umux_coef_1_n (.clk(clk),
.gclk_en(clk_en),.data_0_in(coef_st_0_mac_1_n),
.data_1_in(coef_st_1_mac_1_n),
.data_out(coef_st_1_n),
.sel(coef_set_ext));
defparam Umux_coef_1_n.IN_WIDTH = COEF_WIDTH;
wire [7:0] coef_st_2_n;
mux_16_cen Umux_coef_2_n (.clk(clk),
.gclk_en(clk_en),.data_0_in(coef_st_0_mac_2_n),
.data_1_in(coef_st_1_mac_2_n),
.data_out(coef_st_2_n),
.sel(coef_set_ext));
defparam Umux_coef_2_n.IN_WIDTH = COEF_WIDTH;
wire [7:0] coef_st_3_n;
mux_16_cen Umux_coef_3_n (.clk(clk),
.gclk_en(clk_en),.data_0_in(coef_st_0_mac_3_n),
.data_1_in(coef_st_1_mac_3_n),
.data_out(coef_st_3_n),
.sel(coef_set_ext));
defparam Umux_coef_3_n.IN_WIDTH = COEF_WIDTH;
wire [7:0] coef_st_4_n;
mux_16_cen Umux_coef_4_n (.clk(clk),
.gclk_en(clk_en),.data_0_in(coef_st_0_mac_4_n),
.data_1_in(coef_st_1_mac_4_n),
.data_out(coef_st_4_n),
.sel(coef_set_ext));
defparam Umux_coef_4_n.IN_WIDTH = COEF_WIDTH;
wire [7:0] coef_st_5_n;
mux_16_cen Umux_coef_5_n (.clk(clk),
.gclk_en(clk_en),.data_0_in(coef_st_0_mac_5_n),
.data_1_in(coef_st_1_mac_5_n),
.data_out(coef_st_5_n),
.sel(coef_set_ext));
defparam Umux_coef_5_n.IN_WIDTH = COEF_WIDTH;
wire [7:0] coef_st_6_n;
mux_16_cen Umux_coef_6_n (.clk(clk),
.gclk_en(clk_en),.data_0_in(coef_st_0_mac_6_n),
.data_1_in(coef_st_1_mac_6_n),
.data_out(coef_st_6_n),
.sel(coef_set_ext));
defparam Umux_coef_6_n.IN_WIDTH = COEF_WIDTH;
wire [7:0] coef_st_7_n;
mux_16_cen Umux_coef_7_n (.clk(clk),
.gclk_en(clk_en),.data_0_in(coef_st_0_mac_7_n),
.data_1_in(coef_st_1_mac_7_n),
.data_out(coef_st_7_n),
.sel(coef_set_ext));
defparam Umux_coef_7_n.IN_WIDTH = COEF_WIDTH;
wire [7:0] coef_st_8_n;
mux_16_cen Umux_coef_8_n (.clk(clk),
.gclk_en(clk_en),.data_0_in(coef_st_0_mac_8_n),
.data_1_in(coef_st_1_mac_8_n),
.data_out(coef_st_8_n),
.sel(coef_set_ext));
defparam Umux_coef_8_n.IN_WIDTH = COEF_WIDTH;
wire [7:0] coef_st_9_n;
mux_16_cen Umux_coef_9_n (.clk(clk),
.gclk_en(clk_en),.data_0_in(coef_st_0_mac_9_n),
.data_1_in(coef_st_1_mac_9_n),
.data_out(coef_st_9_n),
.sel(coef_set_ext));
defparam Umux_coef_9_n.IN_WIDTH = COEF_WIDTH;
wire [7:0] coef_st_10_n;
mux_16_cen Umux_coef_10_n (.clk(clk),
.gclk_en(clk_en),.data_0_in(coef_st_0_mac_10_n),
.data_1_in(coef_st_1_mac_10_n),
.data_out(coef_st_10_n),
.sel(coef_set_ext));
defparam Umux_coef_10_n.IN_WIDTH = COEF_WIDTH;
wire [7:0] coef_st_11_n;
mux_16_cen Umux_coef_11_n (.clk(clk),
.gclk_en(clk_en),.data_0_in(coef_st_0_mac_11_n),
.data_1_in(coef_st_1_mac_11_n),
.data_out(coef_st_11_n),
.sel(coef_set_ext));
defparam Umux_coef_11_n.IN_WIDTH = COEF_WIDTH;
wire [7:0] coef_st_12_n;
mux_16_cen Umux_coef_12_n (.clk(clk),
.gclk_en(clk_en),.data_0_in(coef_st_0_mac_12_n),
.data_1_in(coef_st_1_mac_12_n),
.data_out(coef_st_12_n),
.sel(coef_set_ext));
defparam Umux_coef_12_n.IN_WIDTH = COEF_WIDTH;




wire [17:0] mlu_resx_0_n;
mlu_inf_2reg Umlu_0_n (.clk(clk), .data_in(tdl_dat_0_n_d), .coef_in(coef_st_0_n), .clk_en(clk_en), .mlu_out(mlu_resx_0_n) );
defparam Umlu_0_n.DATA_WIDTH = 10;
defparam Umlu_0_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_0_n.PIPE = 2;
defparam Umlu_0_n.DSP_USE = "YES";
wire [17:0] mlu_res_0_n;
mac_tl Umtl_0_n             (.clk(clk), 
             .data_in(mlu_resx_0_n),
             .data_out(mlu_res_0_n));
defparam Umtl_0_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_1_n;
mlu_inf_2reg Umlu_1_n (.clk(clk), .data_in(tdl_dat_1_n_d), .coef_in(coef_st_1_n), .clk_en(clk_en), .mlu_out(mlu_resx_1_n) );
defparam Umlu_1_n.DATA_WIDTH = 10;
defparam Umlu_1_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_1_n.PIPE = 2;
defparam Umlu_1_n.DSP_USE = "YES";
wire [17:0] mlu_res_1_n;
mac_tl Umtl_1_n             (.clk(clk), 
             .data_in(mlu_resx_1_n),
             .data_out(mlu_res_1_n));
defparam Umtl_1_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_2_n;
mlu_inf_2reg Umlu_2_n (.clk(clk), .data_in(tdl_dat_2_n_d), .coef_in(coef_st_2_n), .clk_en(clk_en), .mlu_out(mlu_resx_2_n) );
defparam Umlu_2_n.DATA_WIDTH = 10;
defparam Umlu_2_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_2_n.PIPE = 2;
defparam Umlu_2_n.DSP_USE = "YES";
wire [17:0] mlu_res_2_n;
mac_tl Umtl_2_n             (.clk(clk), 
             .data_in(mlu_resx_2_n),
             .data_out(mlu_res_2_n));
defparam Umtl_2_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_3_n;
mlu_inf_2reg Umlu_3_n (.clk(clk), .data_in(tdl_dat_3_n_d), .coef_in(coef_st_3_n), .clk_en(clk_en), .mlu_out(mlu_resx_3_n) );
defparam Umlu_3_n.DATA_WIDTH = 10;
defparam Umlu_3_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_3_n.PIPE = 2;
defparam Umlu_3_n.DSP_USE = "YES";
wire [17:0] mlu_res_3_n;
mac_tl Umtl_3_n             (.clk(clk), 
             .data_in(mlu_resx_3_n),
             .data_out(mlu_res_3_n));
defparam Umtl_3_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_4_n;
mlu_inf_2reg Umlu_4_n (.clk(clk), .data_in(tdl_dat_4_n_d), .coef_in(coef_st_4_n), .clk_en(clk_en), .mlu_out(mlu_resx_4_n) );
defparam Umlu_4_n.DATA_WIDTH = 10;
defparam Umlu_4_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_4_n.PIPE = 2;
defparam Umlu_4_n.DSP_USE = "YES";
wire [17:0] mlu_res_4_n;
mac_tl Umtl_4_n             (.clk(clk), 
             .data_in(mlu_resx_4_n),
             .data_out(mlu_res_4_n));
defparam Umtl_4_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_5_n;
mlu_inf_2reg Umlu_5_n (.clk(clk), .data_in(tdl_dat_5_n_d), .coef_in(coef_st_5_n), .clk_en(clk_en), .mlu_out(mlu_resx_5_n) );
defparam Umlu_5_n.DATA_WIDTH = 10;
defparam Umlu_5_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_5_n.PIPE = 2;
defparam Umlu_5_n.DSP_USE = "YES";
wire [17:0] mlu_res_5_n;
mac_tl Umtl_5_n             (.clk(clk), 
             .data_in(mlu_resx_5_n),
             .data_out(mlu_res_5_n));
defparam Umtl_5_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_6_n;
mlu_inf_2reg Umlu_6_n (.clk(clk), .data_in(tdl_dat_6_n_d), .coef_in(coef_st_6_n), .clk_en(clk_en), .mlu_out(mlu_resx_6_n) );
defparam Umlu_6_n.DATA_WIDTH = 10;
defparam Umlu_6_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_6_n.PIPE = 2;
defparam Umlu_6_n.DSP_USE = "YES";
wire [17:0] mlu_res_6_n;
mac_tl Umtl_6_n             (.clk(clk), 
             .data_in(mlu_resx_6_n),
             .data_out(mlu_res_6_n));
defparam Umtl_6_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_7_n;
mlu_inf_2reg Umlu_7_n (.clk(clk), .data_in(tdl_dat_7_n_d), .coef_in(coef_st_7_n), .clk_en(clk_en), .mlu_out(mlu_resx_7_n) );
defparam Umlu_7_n.DATA_WIDTH = 10;
defparam Umlu_7_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_7_n.PIPE = 2;
defparam Umlu_7_n.DSP_USE = "YES";
wire [17:0] mlu_res_7_n;
mac_tl Umtl_7_n             (.clk(clk), 
             .data_in(mlu_resx_7_n),
             .data_out(mlu_res_7_n));
defparam Umtl_7_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_8_n;
mlu_inf_2reg Umlu_8_n (.clk(clk), .data_in(tdl_dat_8_n_d), .coef_in(coef_st_8_n), .clk_en(clk_en), .mlu_out(mlu_resx_8_n) );
defparam Umlu_8_n.DATA_WIDTH = 10;
defparam Umlu_8_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_8_n.PIPE = 2;
defparam Umlu_8_n.DSP_USE = "YES";
wire [17:0] mlu_res_8_n;
mac_tl Umtl_8_n             (.clk(clk), 
             .data_in(mlu_resx_8_n),
             .data_out(mlu_res_8_n));
defparam Umtl_8_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_9_n;
mlu_inf_2reg Umlu_9_n (.clk(clk), .data_in(tdl_dat_9_n_d), .coef_in(coef_st_9_n), .clk_en(clk_en), .mlu_out(mlu_resx_9_n) );
defparam Umlu_9_n.DATA_WIDTH = 10;
defparam Umlu_9_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_9_n.PIPE = 2;
defparam Umlu_9_n.DSP_USE = "YES";
wire [17:0] mlu_res_9_n;
mac_tl Umtl_9_n             (.clk(clk), 
             .data_in(mlu_resx_9_n),
             .data_out(mlu_res_9_n));
defparam Umtl_9_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_10_n;
mlu_inf_2reg Umlu_10_n (.clk(clk), .data_in(tdl_dat_10_n_d), .coef_in(coef_st_10_n), .clk_en(clk_en), .mlu_out(mlu_resx_10_n) );
defparam Umlu_10_n.DATA_WIDTH = 10;
defparam Umlu_10_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_10_n.PIPE = 2;
defparam Umlu_10_n.DSP_USE = "YES";
wire [17:0] mlu_res_10_n;
mac_tl Umtl_10_n             (.clk(clk), 
             .data_in(mlu_resx_10_n),
             .data_out(mlu_res_10_n));
defparam Umtl_10_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_11_n;
mlu_inf_2reg Umlu_11_n (.clk(clk), .data_in(tdl_dat_11_n_d), .coef_in(coef_st_11_n), .clk_en(clk_en), .mlu_out(mlu_resx_11_n) );
defparam Umlu_11_n.DATA_WIDTH = 10;
defparam Umlu_11_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_11_n.PIPE = 2;
defparam Umlu_11_n.DSP_USE = "YES";
wire [17:0] mlu_res_11_n;
mac_tl Umtl_11_n             (.clk(clk), 
             .data_in(mlu_resx_11_n),
             .data_out(mlu_res_11_n));
defparam Umtl_11_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_12_n;
mlu_inf_2reg Umlu_12_n (.clk(clk), .data_in(tdl_dat_12_n_d), .coef_in(coef_st_12_n), .clk_en(clk_en), .mlu_out(mlu_resx_12_n) );
defparam Umlu_12_n.DATA_WIDTH = 10;
defparam Umlu_12_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_12_n.PIPE = 2;
defparam Umlu_12_n.DSP_USE = "YES";
wire [17:0] mlu_res_12_n;
mac_tl Umtl_12_n             (.clk(clk), 
             .data_in(mlu_resx_12_n),
             .data_out(mlu_res_12_n));
defparam Umtl_12_n.DATA_WIDTH = 18;

wire [18:0] tree_l_0_n_0_n;
sadd_c_cen Uaddl_0_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_0_n), .bin(mlu_res_1_n), .res(tree_l_0_n_0_n) );
defparam Uaddl_0_n_0_n.IN_WIDTH = 18;
defparam Uaddl_0_n_0_n.PIPE_DEPTH = 1;
wire [18:0] tree_l_0_n_1_n;
sadd_c_cen Uaddl_0_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_2_n), .bin(mlu_res_3_n), .res(tree_l_0_n_1_n) );
defparam Uaddl_0_n_1_n.IN_WIDTH = 18;
defparam Uaddl_0_n_1_n.PIPE_DEPTH = 1;
wire [18:0] tree_l_0_n_2_n;
sadd_c_cen Uaddl_0_n_2_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_4_n), .bin(mlu_res_5_n), .res(tree_l_0_n_2_n) );
defparam Uaddl_0_n_2_n.IN_WIDTH = 18;
defparam Uaddl_0_n_2_n.PIPE_DEPTH = 1;
wire [18:0] tree_l_0_n_3_n;
sadd_c_cen Uaddl_0_n_3_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_6_n), .bin(mlu_res_7_n), .res(tree_l_0_n_3_n) );
defparam Uaddl_0_n_3_n.IN_WIDTH = 18;
defparam Uaddl_0_n_3_n.PIPE_DEPTH = 1;
wire [18:0] tree_l_0_n_4_n;
sadd_c_cen Uaddl_0_n_4_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_8_n), .bin(mlu_res_9_n), .res(tree_l_0_n_4_n) );
defparam Uaddl_0_n_4_n.IN_WIDTH = 18;
defparam Uaddl_0_n_4_n.PIPE_DEPTH = 1;
wire [18:0] tree_l_0_n_5_n;
sadd_c_cen Uaddl_0_n_5_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_10_n), .bin(mlu_res_11_n), .res(tree_l_0_n_5_n) );
defparam Uaddl_0_n_5_n.IN_WIDTH = 18;
defparam Uaddl_0_n_5_n.PIPE_DEPTH = 1;
wire [18:0] tree_l_0_n_6_n;
sadd_c_cen Uaddl_0_n_6_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_12_n), .bin(18'd0), .res(tree_l_0_n_6_n) );
defparam Uaddl_0_n_6_n.IN_WIDTH = 18;
defparam Uaddl_0_n_6_n.PIPE_DEPTH = 1;

wire [19:0] tree_l_1_n_0_n;
sadd_cen Uaddl_1_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_0_n), .bin(tree_l_0_n_1_n), .res(tree_l_1_n_0_n) );
defparam Uaddl_1_n_0_n.IN_WIDTH = 19;
defparam Uaddl_1_n_0_n.PIPE_DEPTH = 1;
wire [19:0] tree_l_1_n_1_n;
sadd_cen Uaddl_1_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_2_n), .bin(tree_l_0_n_3_n), .res(tree_l_1_n_1_n) );
defparam Uaddl_1_n_1_n.IN_WIDTH = 19;
defparam Uaddl_1_n_1_n.PIPE_DEPTH = 1;
wire [19:0] tree_l_1_n_2_n;
sadd_cen Uaddl_1_n_2_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_4_n), .bin(tree_l_0_n_5_n), .res(tree_l_1_n_2_n) );
defparam Uaddl_1_n_2_n.IN_WIDTH = 19;
defparam Uaddl_1_n_2_n.PIPE_DEPTH = 1;
wire [19:0] tree_l_1_n_3_n;
sadd_cen Uaddl_1_n_3_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_6_n), .bin(19'd0), .res(tree_l_1_n_3_n) );
defparam Uaddl_1_n_3_n.IN_WIDTH = 19;
defparam Uaddl_1_n_3_n.PIPE_DEPTH = 1;

wire [20:0] tree_l_2_n_0_n;
sadd_reg_top_cen Uaddl_2_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_1_n_0_n), .bin(tree_l_1_n_1_n), .res(tree_l_2_n_0_n) );
defparam Uaddl_2_n_0_n.IN_WIDTH = 20;
defparam Uaddl_2_n_0_n.PIPE_DEPTH = 1;
wire [20:0] tree_l_2_n_1_n;
sadd_reg_top_cen Uaddl_2_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_1_n_2_n), .bin(tree_l_1_n_3_n), .res(tree_l_2_n_1_n) );
defparam Uaddl_2_n_1_n.IN_WIDTH = 20;
defparam Uaddl_2_n_1_n.PIPE_DEPTH = 1;

wire [21:0] tree_l_3_n_0_n;
sadd_reg_top_cen Uaddl_3_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_2_n_0_n), .bin(tree_l_2_n_1_n), .res(tree_l_3_n_0_n) );
defparam Uaddl_3_n_0_n.IN_WIDTH = 21;
defparam Uaddl_3_n_0_n.PIPE_DEPTH = 1;

wire [21:0] fir_mc_res;
assign fir_mc_res=tree_l_3_n_0_n;
wire [20:0] fir_acc_in;
wire [20:0] fir_temp_res;
wire [20:0] fir_acc_in_reg;
assign fir_acc_in = fir_mc_res[ACCUM_WIDTH-1:0];
lc_store_cen Uaccum_reg (.clk(clk), .ce(1'b1), .gclk_en(clk_en),.rst(rst), .data_in(fir_acc_in), .q(fir_acc_in_reg) );
defparam Uaccum_reg.WIDTH = ACCUM_WIDTH;
maccum_cen Usa (.clk(clk), .gclk_en(clk_en),.rst(acc_rst_out), .ain(fir_acc_in_reg), .accum_out(fir_temp_res));
defparam Usa.WIDTH_A = ACCUM_WIDTH;
wire [20:0] fir_int_res;
lc_store_cen Ures_reg (.clk(clk), .ce(done_int), .rst(rst), .gclk_en(clk_en),.data_in(fir_temp_res[ACCUM_WIDTH-1:0]), .q(fir_int_res) );
defparam Ures_reg.WIDTH = ACCUM_WIDTH;
assign fir_result = fir_int_res;
mcv_ctrl_nc ctrl(.rst(rst), .clk(clk), .acc_rst_out(acc_rst_out),.clk_en(clk_en),
 .done_int(done_int), .rdy_int(rdy_int), .coef_ld(coef_ld), 
.done(done), .data_ld(data_ld), .rdy_to_ld(rdy_to_ld));
defparam ctrl.REG_LEN   = 4;
defparam ctrl.PIPE_DLY  = 4;
defparam ctrl.BASE_CYCLE  = 3;
defparam ctrl.NO_SYM   = 1; 
defparam ctrl.IS_INT   = 0; 

endmodule
